### ISSUE TITLE
Criação de uma página sobre

### ISSUE THREAD

**Issue by HeloisaBorchardt** [HeloisaLouzada/GitHubMaster#3]
Você pode criar uma página sobre?

**Comment by HeloisaLouzada** [comment]
A página está em produção

**Comment by HeloisaBorchardt** [comment]
Obrigado!

________________________________
De: Heloísa Louzada ***@***.***>
Enviado: quarta-feira, 11 de setembro de 2024 12:47
Para: HeloisaLouzada/GitHubMaster ***@***.***>
Cc: Heloísa Louzada Borchardt Gomes ***@***.***>; Author ***@***.***>
Assunto: Re: [HeloisaLouzada/GitHubMaster] Criação de uma página sobre (Issue #3)

Você não costuma receber emails de ***@***.*** Saiba por que isso é importante<https://aka.ms/LearnAboutSenderIdentification>

A página está em produção
